name: auto-release

on:[push]
  workflow_dispatch:

jobs:
  runs-on: ubuntu-latest
  print-branch:
    - run: echo "${{github.base_ref}}   ${{github.head_ref}}"


  create-release:
    if: ${{ github.event.pull_request.merged &&
        (github.base_ref == 'master' && contains('release' , github.head_ref)) }}

    steps:
     - name: Extract branch name
       shell: bash
       run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
       id: extract_branch

     - name: Create Release ${{ github.event.pull_request.title }}
       uses: "marvinpinto/action-automatic-releases@latest"
       with:
         repo_token: "${{ secrets.GH_TOKEN }}"
         automatic_release_tag: "${{ steps.extract_branch.outputs.branch }}"