name: auto-release

on:
  pull_request:
    types: [ closed ]
  workflow_dispatch:

jobs:
  create-release:
    if: ${{ github.event.pull_request.merged &&
        (github.base_ref == 'master' || github.base_ref == 'dev') }}
    runs-on: ubuntu-latest

    env:
      PRE_RELEASE: ${{ github.base_ref == 'dev' }}

    steps:
      - name: Create Release ${{ github.event.pull_request.title }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          prerelease: ${{ env.PRE_RELEASE }}
          automatic_release_tag: "New version from ${{ github.head_ref }}"